# Generated by Django 4.1.7 on 2023-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('jobTitle', models.JSONField(null=True)),
            ],
        ),
    ]
