# Generated by Django 4.1.7 on 2023-03-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='age',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='jobTitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='about',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
