# Generated by Django 4.1.7 on 2023-03-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_remove_about_age_remove_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='message',
        ),
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='about',
            name='jobTitle',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
